---
# role-rhel10-upgrader/defaults/main.yml

rhsm_username: "{{ vault_rhsm_username | default(lookup('env', 'RHSM_USERNAME'), true) }}"
rhsm_password: "{{ vault_rhsm_password | default(lookup('env', 'RHSM_PASSWORD'), true) }}"

activationkey: "{{ vault_activationkey | default(lookup('env', 'ACTIVATION_KEY'), true) }}"
rhsm_poolid: "{{ vault_rhsm_poolid | default(lookup('env', 'RHSM_POOLID'), true) }}"
cloud_provider: "{{ vault_cloud_provider | default(lookup('env', 'CLOUD_PROVIDER'), true) | default('', true) }}"
auto_config: "{{ vault_auto_config | default(lookup('env', 'AUTO_CONFIG'), true) | default('', true) }}"

rhsm_repositories:
  -  rhel-9-for-x86_64-baseos-rpms
  -  rhel-9-for-x86_64-appstream-rpms

malware_detection: false

# List to collect any issues found during post-upgrade verification
upgrade_issues: []