---
# role-rhel10-upgrader/tasks/repositories.yml

- name: Enable a RHSM repository
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rhsm_repositories }}"
  when: rhsm_repositories is defined

- name: Lock the release version to 9.6 to permit the upgrade to RHEL 10
  community.general.redhat_subscription:
    state: present
    release: "9.6"

- name: Install versionlock plugin
  ansible.builtin.dnf:
    name: "python3-dnf-plugin-versionlock"
    state: present

- name: Check for existing DNF version locks
  ansible.builtin.command: dnf versionlock list
  register: versionlock_list
  changed_when: false

- name: Clear DNF version locks
  ansible.builtin.command: dnf versionlock clear
  # DNF usually outputs 1-2 lines of metadata text. If there are more, locks likely exist.
  when: versionlock_list.stdout_lines | length > 2