---
controller_hosts:
  - name: "gazpacho"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.100"

  - name: "torrezno"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.101"

  - name: "target1"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.130"
      fqdn: "target1.cibeles.me"

  - name: "sporcizia"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.154"
      fqdn: "sporcizia.cibeles.me"

  - name: "spazzina"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.205"
      fqdn: "spazzina.cibeles.me"

  - name: "fancazzista"
    inventory: "NUC Inventory"
    variables:
      ansible_host: "192.168.1.29"
      fqdn: "fancazzista.cibeles.me"